services:
  mysql-container:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Vani@1972
      MYSQL_DATABASE: employeedb
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:8080"
    depends_on:
      - mysql-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3309/employeedb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Vani@1972
volumes:
  mysql_data: